"""add_full_schema

Revision ID: 8b4f7528bc23
Revises: 8a02dd849f78
Create Date: 2026-05-08 11:08:15.687059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4f7528bc23'
down_revision: Union[str, Sequence[str], None] = '8a02dd849f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('season_id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('current_tier', sa.Integer(), nullable=True),
    sa.CheckConstraint('current_tier IS NULL OR current_tier BETWEEN 1 AND 8', name='ck_teams_current_tier_range'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_season_id'), 'teams', ['season_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('season_id', sa.String(length=24), nullable=False),
    sa.Column('home_team_id', sa.String(length=24), nullable=False),
    sa.Column('away_team_id', sa.String(length=24), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.CheckConstraint('home_team_id <> away_team_id', name='ck_matches_distinct_teams'),
    sa.CheckConstraint('tier IS NULL OR tier BETWEEN 1 AND 8', name='ck_matches_tier_range'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_away_team_id'), 'matches', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_matches_home_team_id'), 'matches', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_matches_season_id'), 'matches', ['season_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('team_id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=False),
    sa.CheckConstraint('jersey_number BETWEEN 0 AND 99', name='ck_players_jersey_range'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'jersey_number', name='uq_players_team_jersey')
    )
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_table('rallies',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('match_id', sa.String(length=24), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('point_won_by', sa.String(length=8), nullable=True),
    sa.Column('ai_proposed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ai_confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("point_won_by IS NULL OR point_won_by IN ('home', 'away')", name='ck_rallies_point_won_by'),
    sa.CheckConstraint('end_time IS NULL OR end_time >= start_time', name='ck_rallies_time_order'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rallies_match_id'), 'rallies', ['match_id'], unique=False)
    op.create_table('video_assets',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('match_id', sa.String(length=24), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('storage_url', sa.String(length=512), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('raw', 'preview', 'clip')", name='ck_video_assets_kind'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_assets_match_id'), 'video_assets', ['match_id'], unique=False)
    op.create_table('plays',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('rally_id', sa.String(length=24), nullable=False),
    sa.Column('player_id', sa.String(length=24), nullable=True),
    sa.Column('action', sa.Enum('SERVE', 'PASS', 'SET', 'ATTACK', 'BLOCK', 'DIG', 'FREEBALL', name='play_action'), nullable=False),
    sa.Column('result', sa.Enum('SUCCESS', 'ERROR', 'CONTINUED', name='play_result'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=8), nullable=True),
    sa.Column('position', sa.String(length=32), nullable=True),
    sa.Column('ai_suggested', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.CheckConstraint("team IS NULL OR team IN ('home', 'away')", name='ck_plays_team'),
    sa.CheckConstraint('ai_confidence IS NULL OR (ai_confidence >= 0 AND ai_confidence <= 1)', name='ck_plays_ai_confidence_range'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rally_id'], ['rallies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rally_id', 'sequence', deferrable=True, initially='DEFERRED', name='uq_plays_rally_sequence')
    )
    op.create_index(op.f('ix_plays_player_id'), 'plays', ['player_id'], unique=False)
    op.create_index(op.f('ix_plays_rally_id'), 'plays', ['rally_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plays_rally_id'), table_name='plays')
    op.drop_index(op.f('ix_plays_player_id'), table_name='plays')
    op.drop_table('plays')
    op.drop_index(op.f('ix_video_assets_match_id'), table_name='video_assets')
    op.drop_table('video_assets')
    op.drop_index(op.f('ix_rallies_match_id'), table_name='rallies')
    op.drop_table('rallies')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_season_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_away_team_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_teams_season_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('seasons')
    sa.Enum(name='play_result').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='play_action').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
