"""Add week_number and court to matches

Revision ID: dd154cf6a3b1
Revises: b94bf01b50c6
Create Date: 2026-05-15 19:21:42.550115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd154cf6a3b1'
down_revision: Union[str, Sequence[str], None] = 'b94bf01b50c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('week_number', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('court', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'court')
    op.drop_column('matches', 'week_number')
    # ### end Alembic commands ###
