/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Seasons */
        get: operations["list_seasons_seasons_get"];
        put?: never;
        /** Create Season */
        post: operations["create_season_seasons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seasons/{season_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Season */
        get: operations["read_season_seasons__season_id__get"];
        put?: never;
        post?: never;
        /** Delete Season */
        delete: operations["delete_season_seasons__season_id__delete"];
        options?: never;
        head?: never;
        /** Update Season */
        patch: operations["update_season_seasons__season_id__patch"];
        trace?: never;
    };
    "/seasons/{season_id}/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Season Teams */
        get: operations["list_season_teams_seasons__season_id__teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams */
        get: operations["list_teams_teams_get"];
        put?: never;
        /** Create Team */
        post: operations["create_team_teams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Team */
        get: operations["read_team_teams__team_id__get"];
        put?: never;
        post?: never;
        /** Delete Team */
        delete: operations["delete_team_teams__team_id__delete"];
        options?: never;
        head?: never;
        /** Update Team */
        patch: operations["update_team_teams__team_id__patch"];
        trace?: never;
    };
    "/teams/{team_id}/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Team Players */
        get: operations["list_team_players_teams__team_id__players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Players */
        get: operations["list_players_players_get"];
        put?: never;
        /** Create Player */
        post: operations["create_player_players_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Player */
        get: operations["read_player_players__player_id__get"];
        put?: never;
        post?: never;
        /** Delete Player */
        delete: operations["delete_player_players__player_id__delete"];
        options?: never;
        head?: never;
        /** Update Player */
        patch: operations["update_player_players__player_id__patch"];
        trace?: never;
    };
    "/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Matches */
        get: operations["list_matches_matches_get"];
        put?: never;
        /** Create Match */
        post: operations["create_match_matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Match */
        get: operations["read_match_matches__match_id__get"];
        put?: never;
        post?: never;
        /** Delete Match */
        delete: operations["delete_match_matches__match_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Match Stats */
        get: operations["match_stats_matches__match_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}/export.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Match */
        get: operations["export_match_matches__match_id__export_zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Presign */
        post: operations["presign_uploads_presign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{video_id}/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Video Url */
        get: operations["get_video_url_videos__video_id__url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}/rallies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rallies */
        get: operations["list_rallies_matches__match_id__rallies_get"];
        put?: never;
        /** Create Rally */
        post: operations["create_rally_matches__match_id__rallies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rallies/{rally_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Rally */
        delete: operations["delete_rally_rallies__rally_id__delete"];
        options?: never;
        head?: never;
        /** Update Rally */
        patch: operations["update_rally_rallies__rally_id__patch"];
        trace?: never;
    };
    "/rallies/{rally_id}/plays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plays */
        get: operations["list_plays_rallies__rally_id__plays_get"];
        put?: never;
        /** Create Play */
        post: operations["create_play_rallies__rally_id__plays_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plays/{play_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Play */
        delete: operations["delete_play_plays__play_id__delete"];
        options?: never;
        head?: never;
        /** Update Play */
        patch: operations["update_play_plays__play_id__patch"];
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MatchCreate */
        MatchCreate: {
            /** Season Id */
            season_id: string;
            /** Home Team Id */
            home_team_id: string;
            /** Away Team Id */
            away_team_id: string;
            /**
             * Played At
             * Format: date-time
             */
            played_at: string;
            /** Tier */
            tier?: number | null;
            /** Video Key */
            video_key: string;
            /** Video Duration */
            video_duration?: number | null;
        };
        /** MatchRead */
        MatchRead: {
            /** Id */
            id: string;
            /** Season Id */
            season_id: string;
            home_team: components["schemas"]["TeamReadWithPlayers"];
            away_team: components["schemas"]["TeamReadWithPlayers"];
            /**
             * Played At
             * Format: date-time
             */
            played_at: string;
            /** Tier */
            tier: number | null;
            /**
             * Video Assets
             * @default []
             */
            video_assets: components["schemas"]["VideoAssetRead"][];
        };
        /** MatchStatsResponse */
        MatchStatsResponse: {
            home: components["schemas"]["TeamStats"];
            away: components["schemas"]["TeamStats"];
            /** Players */
            players: components["schemas"]["PlayerStats"][];
        };
        /**
         * PlayAction
         * @enum {string}
         */
        PlayAction: "SERVE" | "PASS" | "SET" | "ATTACK" | "BLOCK" | "DIG" | "FREEBALL";
        /** PlayCreate */
        PlayCreate: {
            /** Player Id */
            player_id?: string | null;
            action: components["schemas"]["PlayAction"];
            result: components["schemas"]["PlayResult"];
            /** Sequence */
            sequence: number;
            /** Play Time Seconds */
            play_time_seconds: number;
            /** Team */
            team?: ("home" | "away") | null;
            /** Position */
            position?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** PlayRead */
        PlayRead: {
            /** Id */
            id: string;
            /** Rally Id */
            rally_id: string;
            /** Player Id */
            player_id: string | null;
            action: components["schemas"]["PlayAction"];
            result: components["schemas"]["PlayResult"];
            /** Sequence */
            sequence: number;
            /** Play Time Seconds */
            play_time_seconds: number;
            /** Team */
            team: string | null;
            /** Position */
            position: string | null;
            /** Ai Suggested */
            ai_suggested: boolean;
            /** Ai Confidence */
            ai_confidence: number | null;
            /** Notes */
            notes: string | null;
        };
        /**
         * PlayResult
         * @enum {string}
         */
        PlayResult: "SUCCESS" | "ERROR" | "CONTINUED";
        /** PlayUpdate */
        PlayUpdate: {
            /** Player Id */
            player_id?: string | null;
            action?: components["schemas"]["PlayAction"] | null;
            result?: components["schemas"]["PlayResult"] | null;
            /** Sequence */
            sequence?: number | null;
            /** Play Time Seconds */
            play_time_seconds?: number | null;
            /** Team */
            team?: ("home" | "away") | null;
            /** Position */
            position?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** PlayerCreate */
        PlayerCreate: {
            /** Name */
            name: string;
            /** Team Id */
            team_id: string;
            /** Jersey Number */
            jersey_number: number;
        };
        /** PlayerRead */
        PlayerRead: {
            /** Id */
            id: string;
            /** Team Id */
            team_id: string;
            /** Name */
            name: string;
            /** Jersey Number */
            jersey_number: number;
        };
        /** PlayerStats */
        PlayerStats: {
            /** Player Id */
            player_id: string;
            /** Name */
            name: string;
            /** Jersey Number */
            jersey_number: number;
            /**
             * Team
             * @enum {string}
             */
            team: "home" | "away";
            /**
             * Kills
             * @default 0
             */
            kills: number;
            /**
             * Attack Errors
             * @default 0
             */
            attack_errors: number;
            /**
             * Aces
             * @default 0
             */
            aces: number;
            /**
             * Service Errors
             * @default 0
             */
            service_errors: number;
            /**
             * Blocks
             * @default 0
             */
            blocks: number;
            /**
             * Digs
             * @default 0
             */
            digs: number;
            /**
             * Reception Errors
             * @default 0
             */
            reception_errors: number;
            /**
             * Assists
             * @default 0
             */
            assists: number;
            /**
             * Points
             * @default 0
             */
            points: number;
        };
        /** PlayerUpdate */
        PlayerUpdate: {
            /** Name */
            name?: string | null;
            /** Jersey Number */
            jersey_number?: number | null;
        };
        /** PresignRequest */
        PresignRequest: {
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
        };
        /** PresignResponse */
        PresignResponse: {
            /** Upload Url */
            upload_url: string;
            /** Key */
            key: string;
        };
        /** RallyCreate */
        RallyCreate: {
            /** Start Time */
            start_time: number;
        };
        /** RallyRead */
        RallyRead: {
            /** Id */
            id: string;
            /** Match Id */
            match_id: string;
            /** Start Time */
            start_time: number;
            /** End Time */
            end_time: number | null;
            /** Point Won By */
            point_won_by: string | null;
            /** Ai Proposed */
            ai_proposed: boolean;
            /** Ai Confirmed */
            ai_confirmed: boolean;
            /**
             * Plays
             * @default []
             */
            plays: components["schemas"]["PlayRead"][];
        };
        /** RallyUpdate */
        RallyUpdate: {
            /** Start Time */
            start_time?: number | null;
            /** End Time */
            end_time?: number | null;
            /** Point Won By */
            point_won_by?: ("home" | "away") | null;
            /** Ai Confirmed */
            ai_confirmed?: boolean | null;
        };
        /** SeasonCreate */
        SeasonCreate: {
            /** Name */
            name: string;
        };
        /** SeasonRead */
        SeasonRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SeasonReadWithTeams */
        SeasonReadWithTeams: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Teams
             * @default []
             */
            teams: components["schemas"]["TeamRead"][];
        };
        /** SeasonUpdate */
        SeasonUpdate: {
            /** Name */
            name?: string | null;
        };
        /** TeamCreate */
        TeamCreate: {
            /** Name */
            name: string;
            /** Season Id */
            season_id: string;
            /** Current Tier */
            current_tier?: number | null;
        };
        /** TeamRead */
        TeamRead: {
            /** Id */
            id: string;
            /** Season Id */
            season_id: string;
            /** Name */
            name: string;
            /** Current Tier */
            current_tier: number | null;
        };
        /** TeamReadWithPlayers */
        TeamReadWithPlayers: {
            /** Id */
            id: string;
            /** Season Id */
            season_id: string;
            /** Name */
            name: string;
            /** Current Tier */
            current_tier: number | null;
            /**
             * Players
             * @default []
             */
            players: components["schemas"]["PlayerRead"][];
        };
        /** TeamStats */
        TeamStats: {
            /**
             * Side
             * @enum {string}
             */
            side: "home" | "away";
            /** Team Id */
            team_id: string;
            /** Name */
            name: string;
            /**
             * Score
             * @default 0
             */
            score: number;
            /**
             * Kills
             * @default 0
             */
            kills: number;
            /**
             * Attack Errors
             * @default 0
             */
            attack_errors: number;
            /**
             * Aces
             * @default 0
             */
            aces: number;
            /**
             * Service Errors
             * @default 0
             */
            service_errors: number;
            /**
             * Blocks
             * @default 0
             */
            blocks: number;
            /**
             * Digs
             * @default 0
             */
            digs: number;
            /**
             * Reception Errors
             * @default 0
             */
            reception_errors: number;
            /**
             * Assists
             * @default 0
             */
            assists: number;
        };
        /** TeamUpdate */
        TeamUpdate: {
            /** Name */
            name?: string | null;
            /** Current Tier */
            current_tier?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VideoAssetRead */
        VideoAssetRead: {
            /** Id */
            id: string;
            /** Match Id */
            match_id: string;
            /** Kind */
            kind: string;
            /** Storage Url */
            storage_url: string;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
        };
        /** VideoUrlResponse */
        VideoUrlResponse: {
            /** Url */
            url: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_seasons_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonRead"][];
                };
            };
        };
    };
    create_season_seasons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeasonCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_season_seasons__season_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonReadWithTeams"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_season_seasons__season_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_season_seasons__season_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeasonUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_season_teams_seasons__season_id__teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                season_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRead"][];
                };
            };
        };
    };
    create_team_teams_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_team_teams__team_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamReadWithPlayers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_team_teams__team_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_team_teams__team_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_team_players_teams__team_id__players_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_players_players_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"][];
                };
            };
        };
    };
    create_player_players_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_player_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_player_players__player_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_player_players__player_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matches_matches_get: {
        parameters: {
            query?: {
                season_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_match_matches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_match_matches__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_match_matches__match_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_stats_matches__match_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_match_matches__match_id__export_zip_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presign_uploads_presign_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_url_videos__video_id__url_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rallies_matches__match_id__rallies_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RallyRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rally_matches__match_id__rallies_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RallyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RallyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rally_rallies__rally_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rally_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rally_rallies__rally_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rally_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RallyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RallyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plays_rallies__rally_id__plays_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rally_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_play_rallies__rally_id__plays_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rally_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_play_plays__play_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                play_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_play_plays__play_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                play_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
